### ISSUE TITLE
Main.java - Inner Class

### ISSUE THREAD

**Issue by gglerum** [heartmates01/NewBibliotheek#1]
In `Main.java` staat de class `NewBibliotheek`. Binnen deze class staat de class `Main` waar het bestand ook naar is vernoemd. De mag de buitenste class `NewBibliotheek` weglaten. Dit voegt alleen een extra laag toe aan `Main.java`, maar doet eigenlijk verder niks voor de werking van je applicatie.

Wilde je op deze manier je project `NewBibliotheek` noemen? Als je dat namelijk wilt doen, dan kan dat door:

1. binnen de package `nl.heartmates01` een nieuwe package aanmaken `newbibliotheek` (packages graag met kleine letters).
2. alle andere packages en de class `Main.java` selecteren.
3. rechts klikken op de selectie en kiezen voor "Refactor -> Move Packages or Directories"
4. in het dialoog venster `nl.heartmates01.newbibliotheek` invullen en drukken op "refactor"

**Comment by heartmates01** [comment]
class newbibliotheek weggelaten
