### ISSUE TITLE
Main.java - overige punten

### ISSUE THREAD

**Issue by gglerum** [heartmates01/NewBibliotheek#2]
https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/Main.java#L108-L110

Ik vindt het netjes om te zien dat je de `userInput` method hergebruikt vanuit een andere class. Ik zou de methode well naar de `Main` class verplaatsen. Anders verwijst straks de code in je `MagazineController` naar de `userInput` method in de `BookController`.

We willen altijd voorkomen dat code van één onderdeel (in dit geval `magazine`) afhankelijk wordt van methods of classes van een ander onderdeel van de applicatie. Stel dat we besluiten (om één of andere vage reden) om het gedeelte van boeken te verwijderen, dan zou de hele package `book` verdwijnen en gaat de code in `magazine` stuk omdat het afhankelijk was van de code in de `book` package.

Wat je wel mag doen is methods die meerdere packages gebruiken onderbrengen in de `Main` class, of een andere class die in een package staat waar alle andere packages gebruik van mogen maken.

**Comment by heartmates01** [comment]
userInput staat nu in main
