### ISSUE TITLE
BookController

### ISSUE THREAD

**Issue by gglerum** [heartmates01/NewBibliotheek#3]
https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/book/BookController.java#L12

Dit heb je op een mooie manier opgelost. Het maakt het menu voor de eind gebruiker een stuk overzichtelijker. 

------

https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/book/BookController.java#L68-L90

Ook het tonen van een apart menu voor het retourneren of lenen van boeken vind ik een mooie toevoeging.

Ik zou wel om het overzichtelijk te houden de code van deze case verplaatsen naar een nieuwe method `handleBookActions` (een andere naam voor de method die beter past mag natuurlijk ook). Dit kun je doen door.
1. De code binnen de case te selecteren.
2. rechts op de selectie te klikken en te kiezen voor "Refactor -> Extract Method"
3. pas de naam van de nieuwe methode aan

-----

https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/book/BookController.java#L193-L198

Je hebt hem bijna. Wat je wil doen is elk boek aan `result` toevoegen en dan de gevulde `result` printen na de `for-loop`.

------

https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/book/BookController.java#L216

Class variabelen graag altijd bovenaan plaatsen binnen de class.

**Comment by heartmates01** [comment]
borrowOrReturn nu in eige method & showBooks werkt nu
