### ISSUE TITLE
BookRepository

### ISSUE THREAD

**Issue by gglerum** [heartmates01/NewBibliotheek#4]
https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/book/BookRepository.java#L38-L44

Dit gaat niet helemaal goed. Wat er in deze method gebeurt is dat elke keer wanneer je een lijst ophaalt van alle boeken, worden de boeken opnieuw aan de bestaande lijst toegevoegd. Het enige wat je hier hoeft te doen is de lijst met boeken terug te geven.

```Java
ArrayList<Book> getBooks() {
return allBooks;
}
```

-------

https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/book/BookRepository.java#L46-L55

Hier gebeurt min of meer hetzelfde als bij `getBooks`. Java heeft hier gelukkig een foefje voor.

```Java
List<Book> getBorrowedBooks() {
    return allBooks.stream().filter(Book::hasBeenBorrowed).toList();
}
```
Wat deze code doet is eerst `allBooks` omzetten naar een `stream`: `allBooks.stream()`. Een stream is eigenlijk een soort van `ArrayList` waar je heel veel bewerkingen tegelijk op kunt doen. 

Op de `stream` roepen we de `filter` method aan: `allBooks.stream().filter(`. De filter method wil graag een referentie naar een method van de `Book` class (dit omdat de stream nu vol zit met `Book` objecten. De method die de filter method wil hebben moet een boolean teruggeven; bij true wordt het object in de stream behouden, bij false wordt hij uit de stream gehaald. We geven hier aan de `filter` method de referentie naar de `hasBeenBorrowed` method van de `Book` class. Dit doen we door eerst te verwijzen naar de `Book` class en dan met `::` aan te geven dat het om de method `hasBeenBorrowed` van de `Book` class gaat: `.filter(Book::hasBeenBorrowed)`.

Nu hebben we als het goed is alleen maar `Book`  objecten in de stream die uitgeleend zijn. Het laatste wat we nu nog moeten doen is de `stream` omzetten naar een `List` met `.toList()`.

De stream kan alleen de `interface` van `ArrayList` teruggeven en niet een `ArrayList` zelf. Vandaar dat het return type van de method is gewijzigd van `ArrayList<Book>` naar `List<Book>`.

-----

https://github.com/heartmates01/NewBibliotheek/blob/27f338e988b03654fc811112866d43445329a6bd/src/main/java/nl/heartmates01/book/BookRepository.java#L57-L65

Voor deze method kunnen we precies het zelfde doen als bij `getBorrowedBooks`, maar dan met een kleine toevoeging.

```Java
List<Book> getBorrowedBooks() {
    return allBooks.stream().filter(Predicate.not(Book::hasBeenBorrowed)).toList();
}
```

Binnen de `filter` method roepen we nu `Predicate.not()` aan op de "return waarde" van `Book::hasBeenBorrowed`. Wat we hier eigenlijk doen is van `true` een `false` maken, en van `false` een `true`.

**Comment by heartmates01** [comment]
hoord nu goed te werken
